/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SneekRouteImport } from './routes/sneek'
import { Route as IndexRouteImport } from './routes/index'

const SneekRoute = SneekRouteImport.update({
  id: '/sneek',
  path: '/sneek',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sneek': typeof SneekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sneek': typeof SneekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sneek': typeof SneekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sneek'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sneek'
  id: '__root__' | '/' | '/sneek'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SneekRoute: typeof SneekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sneek': {
      id: '/sneek'
      path: '/sneek'
      fullPath: '/sneek'
      preLoaderRoute: typeof SneekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SneekRoute: SneekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
